auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  per_stream_rate_limit: 10MB
  max_query_parallelism: 64
  split_queries_by_interval: 1h

ingester:
  chunk_encoding: snappy

ruler:
  alertmanager_url: http://localhost:9093

querier:
  max_concurrent: 2048

