name: test
volumes:
  loki:
  promtail:

services:

  loki:
    container_name: loki
    build:
      context: loki/vps
    restart: unless-stopped
    command: -config.file=/etc/loki/config.yaml
    mem_limit: 1024m
    volumes:
      - loki:/loki

  promtail:
    container_name: promtail
    build:
      context: promtail/vps
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - promtail:/data
    command: -config.file=/etc/promtail/config.yml

  bash:
    image: bash
    container_name: bash
    command: ["bash", "-c", "while sleep 3600; do :; done"]

