#volumes:
secrets:
  host_ssh_key:
    file: ~/.ssh/id_rsa

services:

  # https://gist.github.com/cschiewek/246a244ba23da8b9f0e7b11a68bf3285
  # Updated:
  #   https://gist.github.com/paul-krohn/e45f96181b1cf5e536325d1bdee6c949
  # 
  # Requirements:
  #
  # install xquartz
  # in prefs->security, allow incoming network conns
  #
  # Runbook (each time):
  #
  # start xquartz
  # xhost + ${hostname}
  # export HOSTNAME=`hostname`
  #  ubuntu-x11:
  #  build:
  #    context: ubuntu-x11
  #  environment:
  #  - DISPLAY=${HOSTNAME}:0
  #  volumes:
  #  - /tmp/.X11-unix:/tmp/.X11-unix


  ubuntu-cli:
    container_name: ubuntu-cli
    build:
      context: ubuntu
    environment:
    - DISPLAY=${HOSTNAME}:0
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    secrets:
      - host_ssh_key

