volumes:
  atuin_postgres:
  atuin-config:
  caddy-data:
  caddy-config:
  caddy-logs:
  freshrss_data:
  freshrss_extensions:
  portainer:

services:

  atuin:
    restart: always
    container_name: atuin
    image: ghcr.io/atuinsh/atuin:18.2.0
    command: server start
    volumes:
      - "atuin-config:/config"
    links:
      - atuin-db:db
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "false"
      ATUIN_DB_URI: postgres://atuin:${ATUIN_POSTGRES_PASSWORD}@db/atuin

  atuin-db:
    image: postgres:14
    container_name: atuin-db
    restart: unless-stopped
    volumes: # Don't remove permanent storage for index database files!
      - "atuin_postgres:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: atuin
      POSTGRES_PASSWORD: ${ATUIN_POSTGRES_PASSWORD}
      POSTGRES_DB: atuin

  caddy:
    build:
      context: caddy-vps
    container_name: caddy
    privileged: true
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - caddy-logs:/var/log/caddy
      - /run/tailscale.nginx-auth.sock:/run/tailscale.nginx-auth.sock

  bash:
    image: bash
    container_name: bash
    network_mode: host
    command: ["bash", "-c", "sleep 365"]

  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: America/New_York
      CRON_MIN: '3,33'

  # listens on 3000
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    build:
      context: homepage-vps
    volumes:
      # - /path/to/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped

  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
