name: local
volumes:
  atuin_postgres:
  atuin-config:
  caddy-data:
  caddy-config:

services:

  atuin:
    restart: always
    image: ghcr.io/atuinsh/atuin:18.2.0
    command: server start
    volumes:
      - "atuin-config:/config"
    links:
      - atuin-db:db
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "false"
      ATUIN_DB_URI: postgres://atuin:${ATUIN_POSTGRES_PASSWORD}@db/atuin
    labels:
      - homepage.group=My First Group
      - homepage.name=atuin
      - homepage.icon=emby.png
      - homepage.href=https://atuin.sh/
      - homepage.description=Atuin

  atuin-db:
    image: postgres:14
    restart: unless-stopped
    volumes: # Don't remove permanent storage for index database files!
      - "atuin_postgres:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: atuin
      POSTGRES_PASSWORD: ${ATUIN_POSTGRES_PASSWORD}
      POSTGRES_DB: atuin

  caddy:
    build:
      context: ../../caddy/local
    privileged: true
    restart: unless-stopped
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    labels:
      - homepage.group=My First Group
      - homepage.name=caddy
      - homepage.icon=emby.png
      - homepage.href=https://localhost/
      - homepage.description=Caddy

  homepage:
    build:
      context: ../../homepage/local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    restart: unless-stopped
    environment:
      LOG_LEVEL: debug
