name: containers
volumes:
  freshrss_data:
  freshrss_extensions:
  grafana:
  linkding:
  pihole-etc-dnsmasq:
  pihole-etc-pihole:
  portainer:
  prometheus:
  registry:
  livegrep:
  caddy-data:
  caddy-config:
  homeassistant-config:
  tailscale:

services:

  ngrok:
    container_name: ngrok
    build:
      context: ngrok
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yaml"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_NAS_AUTHTOKEN}
    ports:
      - 4041:4040

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      TZ: 'America/Chicago'
      FTLCONF_LOCAL_IPV4: 192.168.0.150
      ServerIP: 192.168.0.150
      WEB_PORT: 8080
      QUERY_LOGGING: "false"
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
    volumes:
      - pihole-etc-pihole:/etc/pihole
      - pihole-etc-dnsmasq:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:8080"

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: nas-tailscale
    volumes:
      - tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_EXTRA_ARGS=--advertise-routes=192.168.0.0/24
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
