global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: "node"
    static_configs:
      - targets:
          - "node-exporter:9100"
  - job_name: "mbpm2"
    static_configs:
      - targets:
          - "100.72.230.10:9100"
  - job_name: "openweather"
    static_configs:
      - targets:
          - "openweather-exporter:9091"

