#!/usr/bin/env bash

mkdir -p ~/.ssh
sudo cp /run/secrets/host_ssh_key $HOME/.ssh/id_rsa
sudo chown -R $USER:$USER $HOME/.ssh

if [ ! -d ~/.dotfiles ]; then

cat <<eos > $HOME/.ssh/config
Host github.com
	StrictHostKeyChecking no
eos

	git clone git@github.com:collinvandyck/dotfiles.git ~/.dotfiles
	rm $HOME/.ssh/config
else
	cd ~/.dotfiles
	git pull
fi

cd ~/.dotfiles
./install-all
exec zsh
