version: '3'
services:
  bash:
    image: bash:latest
    command: 'sleep 10000000000000'
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "false"
    secrets:
      - bash-secret

secrets:
  bash-secret:
    external: true
