name: containers
volumes:
  atuin_postgres:
  atuin-config:
  caddy-data:
  caddy-config:
  caddy-logs:
  freshrss_data:
  freshrss_extensions:
  grafana-storage:
  loki:
  pihole:
  pihole_dnsmasq:
  portainer:
  prometheus:
  promtail:

secrets:
  glances_pw:
    file: /root/secrets/glances/collin.pwd
  smb_pw:
    file: /root/secrets/smb/collin.pwd

services:

  caddy:
    build:
      context: caddy
    container_name: caddy
    privileged: true
    network_mode: host
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - caddy-logs:/var/log/caddy
      - /run/tailscale.nginx-auth.sock:/run/tailscale.nginx-auth.sock

  atuin:
    restart: always
    container_name: atuin
    image: ghcr.io/atuinsh/atuin:18.3.0
    command: server start
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - "atuin-config:/config"
    links:
      - atuin-db:db
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "false"
      ATUIN_DB_URI: postgres://atuin:${ATUIN_POSTGRES_PASSWORD}@db/atuin

  atuin-db:
    image: postgres:14
    container_name: atuin-db
    restart: unless-stopped
    volumes:
      - "atuin_postgres:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: atuin
      POSTGRES_PASSWORD: ${ATUIN_POSTGRES_PASSWORD}
      POSTGRES_DB: atuin

  bash:
    image: bash
    container_name: bash
    command: ["bash", "-c", "while sleep 3600; do :; done"]

  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    ports:
      - "127.0.0.1:8880:80"
    logging:
      options:
        max-size: 10m
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: America/New_York
      CRON_MIN: '3,33'

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    build:
      context: homepage
    ports:
      - "127.0.0.1:8881:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8882:9443"
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  prometheus:
    container_name: prometheus
    hostname: prometheus
    build:
      context: prometheus
    restart: unless-stopped
    volumes:
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - "--storage.tsdb.retention.time=730d"
      - "--storage.tsdb.path=/prometheus/"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  loki:
    container_name: loki
    build:
      context: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/config.yaml
    mem_limit: 1024m
    volumes:
      - loki:/loki

  promtail:
    container_name: promtail
    build:
      context: promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
      - caddy-logs:/var/log/caddy
      - /var/lib/docker/containers:/var/lib/docker/containers
      - promtail:/data
    command: -config.file=/etc/promtail/config.yml

  grafana:
    container_name: grafana
    build:
      context: grafana
    restart: unless-stopped
    ports:
      - "127.0.0.1:8883:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${VPS_GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${VPS_GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana

  glances:
    container_name: glances
    image: nicolargo/glances:latest-full
    restart: unless-stopped
    pid: host
    ports:
      - "127.0.0.1:8884:61208"
    secrets:
      - source: glances_pw
        target: /root/.config/glances/glances.pwd
    environment:
      GLANCES_OPT: "-w --password"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "100.123.179.103:53:53/tcp"
      - "100.123.179.103:53:53/udp"
      - "127.0.0.1:8885:80"
    environment:
      - TZ=America/Chicago
      - WEBPASSWORD=${PIHOLE_PASSWORD}
    volumes:
      - pihole:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped

