name: samba
services:
  samba:
    build: samba
    container_name: samba
    restart: unless-stopped
    environment:
      ACCOUNT_collin: ${SAMBA_COLLIN_PASSWORD}
      UID_collin: 1000
      SAMBA_VOLUME_CONFIG_sharename: "[collin]; path=/shares/collin; available = yes; browsable = yes; writable = yes; read only = no; force user = collin; public = no; guest ok = no"
    cap_add:
     - CAP_NET_ADMIN
    volumes:
      - /shares/collin:/shares/collin
    ports:
      - 100.123.179.103:445:445

