name: ts-ex
services:
  tailscale-authkey1:
    image: tailscale/tailscale:latest
    container_name: ts-authkey-test
    hostname: banana
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ts-authkey:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  nginx-authkey-test:
    image: nginx
    network_mode: service:tailscale-authkey1

  stirling-ts:
    build: stirling-ts
    container_name: stirling-ts
    hostname: pdf
    environment:
      - "TS_EXTRA_ARGS=--advertise-tags=tag:container --reset"
      - TS_SERVE_CONFIG=/config/stirling.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - stirling-ts:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  stirlingpdf:
    image: frooodle/s-pdf:latest
    container_name: stirlingpdf
    network_mode: service:stirling-ts
    depends_on:
      - stirling-ts
    volumes:
      - stirling-config:/configs
      - stirling-data:/usr/share/tesseract-ocr/5/tessdata
    environment:
      - DOCKER_ENABLE_SECURITY=false
    restart: unless-stopped

volumes:
  ts-authkey:
    driver: local
  stirling-ts:
    driver: local
  stirling-config:
    driver: local
  stirling-data:
    driver: local

