volumes:
  atuin_postgres:
  atuin-config:

networks:
  custom:
    external: true

services:

  atuin:
    image: ghcr.io/atuinsh/atuin:18.2.0
    command: server start
    volumes:
      - "atuin-config:/config"
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "false"
    env_file:
      - ./.atuin.env
    networks:
      - custom

  atuin-db:
    image: postgres:14
    volumes:
      - "atuin_postgres:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: atuin
      POSTGRES_DB: atuin
    env_file:
      - ./.atuin-db.env
    networks:
      - custom


