volumes:
  atuin_postgres:
  atuin-config:

services:

  atuin:
    image: ghcr.io/atuinsh/atuin:18.2.0
    command: server start
    volumes:
      - "atuin-config:/config"
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "false"
      ATUIN_DB_URI: "postgres://atuin:changeme123@db/atuin"
      RUST_LOG: debug,atuin_server=debug

  db:
    image: postgres:14
    volumes:
      - "atuin_postgres:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: atuin
      POSTGRES_DB: atuin
      POSTGRES_PASSWORD: changeme123
