name: playground
volumes:
  openwebuidata:
  pipelines:
  langflow-postgres:
  langflow-data:
  chroma-data:

services:
    openwebui:
      image: ghcr.io/open-webui/open-webui:main
      restart: unless-stopped
      ports:
        - 127.0.0.1:8093:8080
      volumes:
        - openwebuidata:/app/backend/data
      environment:
          OLLAMA_BASE_URL: http://ryzen:11434
          OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}

    pipelines:
      image: ghcr.io/open-webui/pipelines:main
      restart: unless-stopped
      ports:
        - 127.0.0.1:8094:9099
      volumes:
        - pipelines:/app/pipelines

    tika:
      image: apache/tika:latest-full
      restart: unless-stopped

    #langflow:
      #build:
        #dockerfile: Dockerfile.langflow
      #restart: unless-stopped
      #ports:
        #- "7860:7860"
      #depends_on:
        #- langflow-postgres
      #environment:
        #LANGFLOW_DATABASE_URL: postgresql://langflow:langflow@langflow-postgres:5432/langflow
        #LANGFLOW_LOG_LEVEL: debug
        #SECRET_KEY: ${LANGFLOW_SECRET_KEY}
        #COLUMNS: 200
      #volumes:
        #- langflow-data:/app/langflow

    langflow:
      build:
        dockerfile: Dockerfile.langflow
      platform: linux/amd64
      pull_policy: always
      restart: unless-stopped
      #ports:
        #- "7860:7860"
      depends_on:
        - langflow-postgres
      environment:
        LANGFLOW_DATABASE_URL: postgresql://langflow:langflow@langflow-postgres:5432/langflow
        LANGFLOW_LOG_LEVEL: debug
        SECRET_KEY: ${LANGFLOW_SECRET_KEY}
        COLUMNS: 200
      volumes:
        - langflow-data:/app/langflow

    langflow-postgres:
      image: postgres:16
      restart: unless-stopped
      environment:
        POSTGRES_USER: langflow
        POSTGRES_PASSWORD: langflow
        POSTGRES_DB: langflow
      volumes:
        - langflow-postgres:/var/lib/postgresql/data

    chroma:
      image: chromadb/chroma
      restart: unless-stopped
      volumes:
        - chroma-data:/index_data

