---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Frequent:
    - HackerNews:
        - abbr: HN
          icon: hackernews
          href: https://news.ycombinator.com/
    - Github:
        - abbr: GH
          href: https://github.com/
    - Youtube:
        - abbr: YT
          icon: youtube
          href: https://youtube.com/

